!pip install imbalanced-learn

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [7]:

# Örnek veri seti
train_df = pd.read_csv("train.csv")  # Veri setinizi yükleyin

train_df.head()

,AccountAge,MonthlyCharges,TotalCharges,SubscriptionType,PaymentMethod,PaperlessBilling,ContentType,MultiDeviceAccess,DeviceRegistered,ViewingHoursPerWeek,...,ContentDownloadsPerMonth,GenrePreference,UserRating,SupportTicketsPerMonth,Gender,WatchlistSize,ParentalControl,SubtitlesEnabled,CustomerID,Churn
0,20,11.055215,221.104302,Premium,Mailed check,No,Both,No,Mobile,36.758104,...,10,Sci-Fi,2.176498,4,Male,3,No,No,CB6SXPNVZA,0
1,57,5.175208,294.986882,Basic,Credit card,Yes,Movies,No,Tablet,32.450568,...,18,Action,3.478632,8,Male,23,No,Yes,S7R2G87O09,0
2,73,12.106657,883.785952,Basic,Mailed check,Yes,Movies,No,Computer,7.395160,...,23,Fantasy,4.238824,6,Male,1,Yes,Yes,EASDC20BDT,0
3,32,7.263743,232.439774,Basic,Electronic check,No,TV Shows,No,Tablet,27.960389,...,30,Drama,4.276013,2,Male,24,Yes,Yes,NPF69NT69N,0
4,57,16.953078,966.325422,Premium,Electronic check,Yes,TV Shows,No,TV,20.083397,...,20,Comedy,3.616170,4,Female,0,No,No,4LGYPK7VOL,0

In [9]:
onehot_columns=["SubscriptionType","PaymentMethod","PaperlessBilling","ContentType","MultiDeviceAccess","DeviceRegistered","GenrePreference","Gender","ParentalControl","SubtitlesEnabled"]

In [10]:
onehot_df=pd.get_dummies(train_df[onehot_columns],dtype=int)
onehot_df.head()

,SubscriptionType_Basic,SubscriptionType_Premium,SubscriptionType_Standard,PaymentMethod_Bank transfer,PaymentMethod_Credit card,PaymentMethod_Electronic check,PaymentMethod_Mailed check,PaperlessBilling_No,PaperlessBilling_Yes,ContentType_Both,...,GenrePreference_Comedy,GenrePreference_Drama,GenrePreference_Fantasy,GenrePreference_Sci-Fi,Gender_Female,Gender_Male,ParentalControl_No,ParentalControl_Yes,SubtitlesEnabled_No,SubtitlesEnabled_Yes
0,0,1,0,0,0,0,1,1,0,1,...,0,0,0,1,0,1,1,0,1,0
1,1,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,1,1,0,0,1
2,1,0,0,0,0,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,1
3,1,0,0,0,0,1,0,1,0,0,...,0,1,0,0,0,1,0,1,0,1
4,0,1,0,0,0,1,0,0,1,0,...,1,0,0,0,1,0,1,0,1,0

In [11]:
newtrain_df=pd.concat([train_df,onehot_df],axis=1)
newtrain_df.head()

,AccountAge,MonthlyCharges,TotalCharges,SubscriptionType,PaymentMethod,PaperlessBilling,ContentType,MultiDeviceAccess,DeviceRegistered,ViewingHoursPerWeek,...,GenrePreference_Comedy,GenrePreference_Drama,GenrePreference_Fantasy,GenrePreference_Sci-Fi,Gender_Female,Gender_Male,ParentalControl_No,ParentalControl_Yes,SubtitlesEnabled_No,SubtitlesEnabled_Yes
0,20,11.055215,221.104302,Premium,Mailed check,No,Both,No,Mobile,36.758104,...,0,0,0,1,0,1,1,0,1,0
1,57,5.175208,294.986882,Basic,Credit card,Yes,Movies,No,Tablet,32.450568,...,0,0,0,0,0,1,1,0,0,1
2,73,12.106657,883.785952,Basic,Mailed check,Yes,Movies,No,Computer,7.395160,...,0,0,1,0,0,1,0,1,0,1
3,32,7.263743,232.439774,Basic,Electronic check,No,TV Shows,No,Tablet,27.960389,...,0,1,0,0,0,1,0,1,0,1
4,57,16.953078,966.325422,Premium,Electronic check,Yes,TV Shows,No,TV,20.083397,...,1,0,0,0,1,0,1,0,1,0

In [12]:
newtrain_df.drop(onehot_columns,axis=1,inplace=True)
newtrain_df.head()

,AccountAge,MonthlyCharges,TotalCharges,ViewingHoursPerWeek,AverageViewingDuration,ContentDownloadsPerMonth,UserRating,SupportTicketsPerMonth,WatchlistSize,CustomerID,...,GenrePreference_Comedy,GenrePreference_Drama,GenrePreference_Fantasy,GenrePreference_Sci-Fi,Gender_Female,Gender_Male,ParentalControl_No,ParentalControl_Yes,SubtitlesEnabled_No,SubtitlesEnabled_Yes
0,20,11.055215,221.104302,36.758104,63.531377,10,2.176498,4,3,CB6SXPNVZA,...,0,0,0,1,0,1,1,0,1,0
1,57,5.175208,294.986882,32.450568,25.725595,18,3.478632,8,23,S7R2G87O09,...,0,0,0,0,0,1,1,0,0,1
2,73,12.106657,883.785952,7.395160,57.364061,23,4.238824,6,1,EASDC20BDT,...,0,0,1,0,0,1,0,1,0,1
3,32,7.263743,232.439774,27.960389,131.537507,30,4.276013,2,24,NPF69NT69N,...,0,1,0,0,0,1,0,1,0,1
4,57,16.953078,966.325422,20.083397,45.356653,20,3.616170,4,0,4LGYPK7VOL,...,1,0,0,0,1,0,1,0,1,0

In [13]:
newtrain_df.set_index("CustomerID",inplace=True)
newtrain_df.index.name=None

In [14]:
scaled_columns=['AccountAge', 'MonthlyCharges', 'TotalCharges', 'ViewingHoursPerWeek',
       'AverageViewingDuration', 'ContentDownloadsPerMonth', 'UserRating',
       'SupportTicketsPerMonth', 'WatchlistSize']

In [15]:
from sklearn.preprocessing import MinMaxScaler

# Min-Max Scaler 
scaler = MinMaxScaler()

df_scaled = scaler.fit_transform(newtrain_df[scaled_columns])

df_scaled = pd.DataFrame(df_scaled, columns=scaled_columns)
df_scaled.head()

,AccountAge,MonthlyCharges,TotalCharges,ViewingHoursPerWeek,AverageViewingDuration,ContentDownloadsPerMonth,UserRating,SupportTicketsPerMonth,WatchlistSize
0,0.161017,0.404346,0.091044,0.916881,0.334464,0.204082,0.294124,0.444444,0.125000
1,0.474576,0.012343,0.122169,0.806430,0.118430,0.367347,0.619659,0.888889,0.958333
2,0.610169,0.474443,0.370216,0.163978,0.299222,0.469388,0.809708,0.666667,0.041667
3,0.262712,0.151580,0.095819,0.691296,0.723074,0.612245,0.819005,0.222222,1.000000
4,0.474576,0.797540,0.404988,0.489320,0.230608,0.408163,0.654044,0.444444,0.000000

In [16]:
droped_newtrain_df=newtrain_df.drop(scaled_columns,axis=1)
droped_newtrain_df.head(1)

,Churn,SubscriptionType_Basic,SubscriptionType_Premium,SubscriptionType_Standard,PaymentMethod_Bank transfer,PaymentMethod_Credit card,PaymentMethod_Electronic check,PaymentMethod_Mailed check,PaperlessBilling_No,PaperlessBilling_Yes,...,GenrePreference_Comedy,GenrePreference_Drama,GenrePreference_Fantasy,GenrePreference_Sci-Fi,Gender_Female,Gender_Male,ParentalControl_No,ParentalControl_Yes,SubtitlesEnabled_No,SubtitlesEnabled_Yes
CB6SXPNVZA,0,0,1,0,0,0,0,1,1,0,...,0,0,0,1,0,1,1,0,1,0

In [17]:
droped_newtrain_df.reset_index(inplace=True)
droped_newtrain_df=droped_newtrain_df.iloc[:,1:]
droped_newtrain_df.head()

,Churn,SubscriptionType_Basic,SubscriptionType_Premium,SubscriptionType_Standard,PaymentMethod_Bank transfer,PaymentMethod_Credit card,PaymentMethod_Electronic check,PaymentMethod_Mailed check,PaperlessBilling_No,PaperlessBilling_Yes,...,GenrePreference_Comedy,GenrePreference_Drama,GenrePreference_Fantasy,GenrePreference_Sci-Fi,Gender_Female,Gender_Male,ParentalControl_No,ParentalControl_Yes,SubtitlesEnabled_No,SubtitlesEnabled_Yes
0,0,0,1,0,0,0,0,1,1,0,...,0,0,0,1,0,1,1,0,1,0
1,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,1,1,0,0,1
2,0,1,0,0,0,0,0,1,0,1,...,0,0,1,0,0,1,0,1,0,1
3,0,1,0,0,0,0,1,0,1,0,...,0,1,0,0,0,1,0,1,0,1
4,0,0,1,0,0,0,1,0,0,1,...,1,0,0,0,1,0,1,0,1,0

In [18]:
con_df=pd.concat([df_scaled,droped_newtrain_df],axis=1)
con_df.head()

,AccountAge,MonthlyCharges,TotalCharges,ViewingHoursPerWeek,AverageViewingDuration,ContentDownloadsPerMonth,UserRating,SupportTicketsPerMonth,WatchlistSize,Churn,...,GenrePreference_Comedy,GenrePreference_Drama,GenrePreference_Fantasy,GenrePreference_Sci-Fi,Gender_Female,Gender_Male,ParentalControl_No,ParentalControl_Yes,SubtitlesEnabled_No,SubtitlesEnabled_Yes
0,0.161017,0.404346,0.091044,0.916881,0.334464,0.204082,0.294124,0.444444,0.125000,0,...,0,0,0,1,0,1,1,0,1,0
1,0.474576,0.012343,0.122169,0.806430,0.118430,0.367347,0.619659,0.888889,0.958333,0,...,0,0,0,0,0,1,1,0,0,1
2,0.610169,0.474443,0.370216,0.163978,0.299222,0.469388,0.809708,0.666667,0.041667,0,...,0,0,1,0,0,1,0,1,0,1
3,0.262712,0.151580,0.095819,0.691296,0.723074,0.612245,0.819005,0.222222,1.000000,0,...,0,1,0,0,0,1,0,1,0,1
4,0.474576,0.797540,0.404988,0.489320,0.230608,0.408163,0.654044,0.444444,0.000000,0,...,1,0,0,0,1,0,1,0,1,0

In [19]:
con_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243787 entries, 0 to 243786
Data columns (total 39 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   AccountAge                      243787 non-null  float64
 1   MonthlyCharges                  243787 non-null  float64
 2   TotalCharges                    243787 non-null  float64
 3   ViewingHoursPerWeek             243787 non-null  float64
 4   AverageViewingDuration          243787 non-null  float64
 5   ContentDownloadsPerMonth        243787 non-null  float64
 6   UserRating                      243787 non-null  float64
 7   SupportTicketsPerMonth          243787 non-null  float64
 8   WatchlistSize                   243787 non-null  float64
 9   Churn                           243787 non-null  int64
 10  SubscriptionType_Basic          243787 non-null  int32
 11  SubscriptionType_Premium        243787 non-null  int32
 12  SubscriptionType_Standard       243787 non-null  int32
 13  PaymentMethod_Bank transfer     243787 non-null  int32
 14  PaymentMethod_Credit card       243787 non-null  int32
 15  PaymentMethod_Electronic check  243787 non-null  int32
 16  PaymentMethod_Mailed check      243787 non-null  int32
 17  PaperlessBilling_No             243787 non-null  int32
 18  PaperlessBilling_Yes            243787 non-null  int32
 19  ContentType_Both                243787 non-null  int32
 20  ContentType_Movies              243787 non-null  int32
 21  ContentType_TV Shows            243787 non-null  int32
 22  MultiDeviceAccess_No            243787 non-null  int32
 23  MultiDeviceAccess_Yes           243787 non-null  int32
 24  DeviceRegistered_Computer       243787 non-null  int32
 25  DeviceRegistered_Mobile         243787 non-null  int32
 26  DeviceRegistered_TV             243787 non-null  int32
 27  DeviceRegistered_Tablet         243787 non-null  int32
 28  GenrePreference_Action          243787 non-null  int32
 29  GenrePreference_Comedy          243787 non-null  int32
 30  GenrePreference_Drama           243787 non-null  int32
 31  GenrePreference_Fantasy         243787 non-null  int32
 32  GenrePreference_Sci-Fi          243787 non-null  int32
 33  Gender_Female                   243787 non-null  int32
 34  Gender_Male                     243787 non-null  int32
 35  ParentalControl_No              243787 non-null  int32
 36  ParentalControl_Yes             243787 non-null  int32
 37  SubtitlesEnabled_No             243787 non-null  int32
 38  SubtitlesEnabled_Yes            243787 non-null  int32
dtypes: float64(9), int32(29), int64(1)
memory usage: 45.6 MB

# Standart Scaler DF

In [1]:
import pandas  as pd

In [2]:
stdscaler_df=pd.read_csv("stdScaled_trainDF.csv")
stdscaler_df.head()

,Unnamed: 0,AccountAge,MonthlyCharges,TotalCharges,ViewingHoursPerWeek,AverageViewingDuration,ContentDownloadsPerMonth,UserRating,SupportTicketsPerMonth,WatchlistSize,...,DeviceRegistered_TV,DeviceRegistered_Tablet,GenrePreference_Action,GenrePreference_Comedy,GenrePreference_Drama,GenrePreference_Fantasy,GenrePreference_Sci-Fi,Gender_Male,ParentalControl_Yes,SubtitlesEnabled_Yes
0,0,-1.167211,-0.327571,-1.015480,1.445760,-0.568767,-1.005550,-0.715003,-0.175623,-1.253704,...,0,0,0,0,0,0,1,1,0,0
1,1,-0.085120,-1.689753,-0.872563,1.062627,-1.317301,-0.450882,0.412146,1.216839,1.526615,...,0,1,1,0,0,0,0,1,0,1
2,2,0.382811,-0.083991,0.266401,-1.165921,-0.690876,-0.104214,1.070180,0.520608,-1.531736,...,0,0,0,0,0,1,0,1,1,1
3,3,-0.816263,-1.205916,-0.993553,0.663249,0.777719,0.381121,1.102372,-0.871855,1.665631,...,0,1,0,0,1,0,0,1,1,1
4,4,-0.085120,1.038747,0.426064,-0.037368,-0.928617,-0.312215,0.531201,-0.175623,-1.670752,...,1,0,0,1,0,0,0,0,0,0

In [15]:
stdscaler_df=stdscaler_df.iloc[:,1:]
stdscaler_df.head(5)

,AccountAge,MonthlyCharges,TotalCharges,ViewingHoursPerWeek,AverageViewingDuration,ContentDownloadsPerMonth,UserRating,SupportTicketsPerMonth,WatchlistSize,Churn,...,DeviceRegistered_TV,DeviceRegistered_Tablet,GenrePreference_Action,GenrePreference_Comedy,GenrePreference_Drama,GenrePreference_Fantasy,GenrePreference_Sci-Fi,Gender_Male,ParentalControl_Yes,SubtitlesEnabled_Yes
0,-1.167211,-0.327571,-1.015480,1.445760,-0.568767,-1.005550,-0.715003,-0.175623,-1.253704,0,...,0,0,0,0,0,0,1,1,0,0
1,-0.085120,-1.689753,-0.872563,1.062627,-1.317301,-0.450882,0.412146,1.216839,1.526615,0,...,0,1,1,0,0,0,0,1,0,1
2,0.382811,-0.083991,0.266401,-1.165921,-0.690876,-0.104214,1.070180,0.520608,-1.531736,0,...,0,0,0,0,0,1,0,1,1,1
3,-0.816263,-1.205916,-0.993553,0.663249,0.777719,0.381121,1.102372,-0.871855,1.665631,0,...,0,1,0,0,1,0,0,1,1,1
4,-0.085120,1.038747,0.426064,-0.037368,-0.928617,-0.312215,0.531201,-0.175623,-1.670752,0,...,1,0,0,1,0,0,0,0,0,0

# ---------------------------------------------------------------------------------------------------------------

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
# Veriyi eğitim ve test setlerine ayırın
X_train, X_test, y_train, y_test = train_test_split(stdscaler_df.drop(["Churn"],axis=1), stdscaler_df.Churn, test_size=0.2, random_state=42)

In [18]:
from imblearn.over_sampling import SMOTE
from collections import Counter

In [19]:
X_train.head(5)

,AccountAge,MonthlyCharges,TotalCharges,ViewingHoursPerWeek,AverageViewingDuration,ContentDownloadsPerMonth,UserRating,SupportTicketsPerMonth,WatchlistSize,SubscriptionType_Basic,...,DeviceRegistered_TV,DeviceRegistered_Tablet,GenrePreference_Action,GenrePreference_Comedy,GenrePreference_Drama,GenrePreference_Fantasy,GenrePreference_Sci-Fi,Gender_Male,ParentalControl_Yes,SubtitlesEnabled_Yes
122411,0.587531,-0.593104,0.090246,-1.180925,0.047932,-0.034881,-0.210265,1.564955,-0.419609,0,...,1,0,0,0,0,0,1,1,0,1
198365,-1.430422,0.444734,-1.137009,1.058066,1.385220,-0.173548,0.119965,0.868724,0.970551,0,...,1,0,0,1,0,0,0,0,0,1
151323,-1.488914,-1.524420,-1.340659,1.470727,-0.542859,1.213123,0.613163,0.520608,1.665631,0,...,1,0,0,0,1,0,0,1,1,1
232410,-0.406823,1.034715,0.063784,0.568832,-0.467898,1.282457,0.575990,0.868724,0.831535,0,...,0,0,0,1,0,0,0,1,1,0
174487,1.698867,-0.787336,0.627248,-1.056102,-0.116587,1.698458,-0.341276,-0.523739,-1.392720,0,...,0,1,1,0,0,0,0,0,1,1

In [20]:


# SMOTE nesnesi oluşturun
smote = SMOTE(random_state=42)

# SMOTE ile aşırı örnekleme uygulayın
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

# Orijinal ve dengelenmiş sınıf dağılımlarını karşılaştırın
print("Orijinal eğitim seti sınıf dağılımı:", Counter(y_train))
print("Dengelenmiş eğitim seti sınıf dağılımı:", Counter(y_train_res))

Orijinal eğitim seti sınıf dağılımı: Counter({0: 159157, 1: 35279})
Dengelenmiş eğitim seti sınıf dağılımı: Counter({0: 159157, 1: 159157})

In [21]:


# Dengelenmiş veri setini DataFrame'e dönüştürün
X_train_res_df = pd.DataFrame(X_train_res, columns=X_train.columns)
y_train_res_df = pd.DataFrame(y_train_res, columns=['Churn'])  # Hedef sütununuzun adını 'Churn' olarak değiştirin

# Özellikler ve hedef sütununu birleştirin
balanced_df = pd.concat([X_train_res_df, y_train_res_df], axis=1)
balanced_df.head()

,AccountAge,MonthlyCharges,TotalCharges,ViewingHoursPerWeek,AverageViewingDuration,ContentDownloadsPerMonth,UserRating,SupportTicketsPerMonth,WatchlistSize,SubscriptionType_Basic,...,DeviceRegistered_Tablet,GenrePreference_Action,GenrePreference_Comedy,GenrePreference_Drama,GenrePreference_Fantasy,GenrePreference_Sci-Fi,Gender_Male,ParentalControl_Yes,SubtitlesEnabled_Yes,Churn
0,0.587531,-0.593104,0.090246,-1.180925,0.047932,-0.034881,-0.210265,1.564955,-0.419609,0,...,0,0,0,0,0,1,1,0,1,0
1,-1.430422,0.444734,-1.137009,1.058066,1.385220,-0.173548,0.119965,0.868724,0.970551,0,...,0,0,1,0,0,0,0,0,1,0
2,-1.488914,-1.524420,-1.340659,1.470727,-0.542859,1.213123,0.613163,0.520608,1.665631,0,...,0,0,0,1,0,0,1,1,1,0
3,-0.406823,1.034715,0.063784,0.568832,-0.467898,1.282457,0.575990,0.868724,0.831535,0,...,0,0,1,0,0,0,1,1,0,0
4,1.698867,-0.787336,0.627248,-1.056102,-0.116587,1.698458,-0.341276,-0.523739,-1.392720,0,...,1,1,0,0,0,0,0,1,1,0

In [22]:
balanced_df.shape

(318314, 34)

In [23]:
# Dengelenmiş veri setini CSV dosyasına kaydedin
balanced_df.to_csv('std_balanced_dataset.csv', index=False)

In [24]:
blncd=pd.read_csv("std_balanced_dataset.csv")
blncd.shape

(318314, 34)

In [25]:
blncd.head()

,AccountAge,MonthlyCharges,TotalCharges,ViewingHoursPerWeek,AverageViewingDuration,ContentDownloadsPerMonth,UserRating,SupportTicketsPerMonth,WatchlistSize,SubscriptionType_Basic,...,DeviceRegistered_Tablet,GenrePreference_Action,GenrePreference_Comedy,GenrePreference_Drama,GenrePreference_Fantasy,GenrePreference_Sci-Fi,Gender_Male,ParentalControl_Yes,SubtitlesEnabled_Yes,Churn
0,0.587531,-0.593104,0.090246,-1.180925,0.047932,-0.034881,-0.210265,1.564955,-0.419609,0,...,0,0,0,0,0,1,1,0,1,0
1,-1.430422,0.444734,-1.137009,1.058066,1.385220,-0.173548,0.119965,0.868724,0.970551,0,...,0,0,1,0,0,0,0,0,1,0
2,-1.488914,-1.524420,-1.340659,1.470727,-0.542859,1.213123,0.613163,0.520608,1.665631,0,...,0,0,0,1,0,0,1,1,1,0
3,-0.406823,1.034715,0.063784,0.568832,-0.467898,1.282457,0.575990,0.868724,0.831535,0,...,0,0,1,0,0,0,1,1,0,0
4,1.698867,-0.787336,0.627248,-1.056102,-0.116587,1.698458,-0.341276,-0.523739,-1.392720,0,...,1,1,0,0,0,0,0,1,1,0